package TheCellar.GUI;

import TheCellar.Charts.BarGraph;
import TheCellar.Charts.LineGraph;
import TheCellar.Charts.PieChart;

import javax.swing.*;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Canvas;
import java.awt.Button;
import java.awt.Color;
import java.awt.Font;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;

// window builder class that creates the gui
// was mainly auto generated by eclipse
public class GamePage {
	private JFrame frame;
	public boolean textListenerEnabled = true;
	
	public static void showWindow() {
		
		
	}
	
	public GamePage() {
		// set title
		frame = new JFrame();
		
		frame.setTitle("The Cellar");

		// set close operation
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setBounds(100, 100, 800, 450);
		frame.getContentPane().setLayout(null);
		
		Button button = new Button("Bank");
		button.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				frame.setVisible(false);
				TheCellar.GUI.BankPage bank = new TheCellar.GUI.BankPage();
				bank.showWindow();
			}
		});
		button.setFont(new Font("SansSerif", Font.BOLD, 18));
		button.setBackground(new Color(248, 242, 22));
		button.setBounds(693, 54, 81, 81);
		frame.getContentPane().add(button);
		
		JButton btnNewButton = new JButton("Pause Menu");
		btnNewButton.setBackground(new Color(255, 4, 0));
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				frame.setVisible(false);
				PauseMenuPage pause = new TheCellar.GUI.PauseMenuPage();
				pause.showWindow();		}
		});
		btnNewButton.setBounds(23, 8, 119, 41);
		frame.getContentPane().add(btnNewButton);
		
		JSlider slider = new JSlider();
		slider.setBounds(10, 374, 151, 26);
		frame.getContentPane().add(slider);
		
		JLabel lblNewLabel = new JLabel("TheCellar.Game Speed");
		lblNewLabel.setBounds(50, 359, 81, 14);
		frame.getContentPane().add(lblNewLabel);
		
		Button button_1 = new Button("Shop");
		button_1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				frame.setVisible(false);
				TheCellar.GUI.ShopPage shop = new ShopPage();
				shop.showWindow();
			}
		});
		button_1.setFont(new Font("SansSerif", Font.BOLD, 18));
		button_1.setBackground(new Color(0, 255, 255));
		button_1.setBounds(693, 141, 81, 81);
		frame.getContentPane().add(button_1);
		
		JLabel lblNewLabel_1 = new JLabel("$10,000");
		lblNewLabel_1.setBackground(new Color(192, 192, 192));
		lblNewLabel_1.setFont(new Font("SansSerif", Font.ITALIC, 18));
		lblNewLabel_1.setBounds(697, 8, 81, 38);
		frame.getContentPane().add(lblNewLabel_1);
		
		Canvas canvas = new Canvas();
		canvas.setBackground(new Color(192, 192, 192));
		canvas.setBounds(0, 54, 161, 289);
		frame.getContentPane().add(canvas);
		
//		Canvas canvas_1 = new Canvas();
//		canvas_1.setBackground(Color.LIGHT_GRAY);
//		canvas_1.setBounds(167, 0, 520, 411);
//		frame.getContentPane().add(canvas_1);

		ArrayList<Double> values = new ArrayList<Double>();
		values.add(10.0);
		values.add(20.0);
		values.add(30.0);
		values.add(40.0);

		ArrayList<String> names = new ArrayList<String>();
		names.add("goggle");
		names.add("bning");
		names.add("brav");
		names.add("brrrr");

		PieChart pieChart = new PieChart(names, values);
		pieChart.setBounds(167, 0, 300, 150);
		frame.getContentPane().add(pieChart);

		LineGraph lineGraph = new LineGraph("time", "company value", values);
		lineGraph.setBounds(167, 160, 300, 150);
		frame.getContentPane().add(lineGraph);

		BarGraph barGraph = new BarGraph("value", names, values);
		barGraph.setBounds(167, 320, 300, 150);
		frame.getContentPane().add(barGraph);


		
		Button button_1_1 = new Button("Hire");
		button_1_1.setFont(new Font("SansSerif", Font.BOLD, 18));
		button_1_1.setBackground(new Color(255, 0, 255));
		button_1_1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				frame.setVisible(false);
				TheCellar.GUI.HirePage chefs = new HirePage();
				chefs.showWindow();	
		}
		});
		button_1_1.setBounds(693, 228, 81, 81);
		frame.getContentPane().add(button_1_1);
		
		
		
		frame.setVisible(true);
	}
	private static void addPopup(Component component, final JPopupMenu popup) {
		component.addMouseListener(new MouseAdapter() {
			public void mousePressed(MouseEvent e) {
				if (e.isPopupTrigger()) {
					showMenu(e);
				}
			}
			public void mouseReleased(MouseEvent e) {
				if (e.isPopupTrigger()) {
					showMenu(e);
				}
			}
			private void showMenu(MouseEvent e) {
				popup.show(e.getComponent(), e.getX(), e.getY());
			}
		});
		
		
	}
		
		public static void main(String[] args) {
			new GamePage();
			showWindow();
			
			
	}

}

