import java.awt.EventQueue;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowListener;

// window builder class that creates the gui
// was mainly auto generated by eclipse
public class WindowBuilder extends JFrame {
	// made variables public to be able to access them from other classes and modified using external listeners
	private JPanel contentPane;
	public boolean textListenerEnabled = true;
	private JTextField textField;
	private JButton quitButton;

	/**
	 * Create the frame.
	 */
	public WindowBuilder() {
		// set title
		setTitle("Palindrome Checker");

		// set close operation
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 500, 247); // set bounds
		contentPane = new JPanel(); // initialize content pane
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5)); // set border

		// set content pane
		setContentPane(contentPane);
		contentPane.setLayout(null);
		
		JButton checkButton = new JButton("Check");
		checkButton.setBounds(401, 183, 77, 19);
		contentPane.add(checkButton);

		// on check button click
		checkButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				// set main toCheck variable to text field text
				Main.toCheck = textField.getText();
			}
		});
		
		JButton resetButton = new JButton("Reset");
		resetButton.setBounds(316, 183, 77, 19);
		contentPane.add(resetButton);

		// on reset button click reset text field
		resetButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				textField.setText("");
			}
		});
		
		textField = new JTextField();
		textField.setBounds(66, 83, 357, 17);
		contentPane.add(textField);
		textField.setColumns(10);
		
		quitButton = new JButton("Quit");
		quitButton.setBounds(8, 183, 77, 19);
		contentPane.add(quitButton);

		// on quit button click
		quitButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				// exit program
				System.exit(0);
			}
		});
	}
}
