import java.awt.EventQueue;
import java.awt.Graphics;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowListener;
import java.awt.Canvas;
import java.awt.Button;
import java.awt.Color;
import java.awt.Font;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

// window builder class that creates the gui
// was mainly auto generated by eclipse
public class WindowBuilder extends JFrame {
	public boolean textListenerEnabled = true;

	/**
	 * Create the frame.
	 */
	public WindowBuilder() {
		// set title
		setTitle("Palindrome Checker");

		// set close operation
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 800, 450);
		
		JPopupMenu popupMenu = new JPopupMenu();
		popupMenu.setBounds(0, 0, 60, 52);
		addPopup(getContentPane(), popupMenu);
		getContentPane().setLayout(null);
		
		Button button = new Button("BANK");
		button.setFont(new Font("SansSerif", Font.BOLD, 18));
		button.setBackground(new Color(248, 242, 22));
		button.setBounds(678, 308, 81, 81);
		getContentPane().add(button);
	}
	private static void addPopup(Component component, final JPopupMenu popup) {
		component.addMouseListener(new MouseAdapter() {
			public void mousePressed(MouseEvent e) {
				if (e.isPopupTrigger()) {
					showMenu(e);
				}
			}
			public void mouseReleased(MouseEvent e) {
				if (e.isPopupTrigger()) {
					showMenu(e);
				}
			}
			private void showMenu(MouseEvent e) {
				popup.show(e.getComponent(), e.getX(), e.getY());
			}
		});
	}
}
