import java.awt.EventQueue;
import java.awt.Graphics;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowListener;
import java.awt.Canvas;

// window builder class that creates the gui
// was mainly auto generated by eclipse
public class WindowBuilder extends JFrame {
	public boolean textListenerEnabled = true;

	/**
	 * Create the frame.
	 */
	public WindowBuilder() {
		// set title
		setTitle("Palindrome Checker");

		// set close operation
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 800, 450);
		getContentPane().setLayout(null);
	}
	public void paint(Graphics g) {
		g.fillRect(175, 350, 450, 50);
	}
}
